import { SidebarMenuItem } from "../types/menu";
import ROUTES from "./ROUTES";
import {
  CiBadgeDollar,
  CiBag1,
  CiBank,
  CiBoxList,
  CiBoxes,
  CiCoins1,
  CiDatabase,
  CiDeliveryTruck,
  CiFaceSmile,
  CiHome,
  CiLocationOn,
  CiMedicalClipboard,
  CiMoneyBill,
  CiPaperplane,
  CiSpeaker,
  CiSquarePlus,
  CiUser,
} from "react-icons/ci";

const menuItems = {
  dashboard: { label: "Home", icon: CiHome, path: ROUTES.home },
  warehouses: {
    label: "Warehouses",
    icon: CiLocationOn,
    path: ROUTES.warehouses,
  },
  departments: {
    label: "Departments",
    icon: CiBank,
    path: ROUTES.departments,
  },
  positions: { label: "Positions", icon: CiSpeaker, path: ROUTES.positions },
  payrolls: { label: "Payrolls", icon: CiLocationOn, path: ROUTES.payroll },
  expenses: { label: "Expenses", icon: CiLocationOn, path: ROUTES.expenses },
  userManagement: {
    label: "User Management",
    icon: CiUser,
    path: ROUTES.userManagement,
  },
  enrollment: {
    label: "User Enrollment",
    icon: CiSquarePlus,
    path: ROUTES.enrollment,
  },
  stockRecords: {
    label: "Stock Records",
    icon: CiBag1,
    path: ROUTES.stockRecords,
  },
  externalStockRecords: {
    label: "External Stock Records",
    icon: CiBank,
    path: ROUTES.externalStockRecords,
  },
  inventoryItems: {
    label: "Inventory Items",
    icon: CiCoins1,
    path: ROUTES.inventoryItems,
  },
  inventoryTransfers: {
    label: "Inventory Transfers",
    icon: CiPaperplane,
    path: ROUTES.inventoryTransfers,
  },
  purchases: { label: "Purchases", icon: CiMoneyBill, path: ROUTES.purchases },
  sales: { label: "Sales", icon: CiBadgeDollar, path: ROUTES.sales },
  externalDispatch: {
    label: "Logistics Dispatch",
    icon: CiDeliveryTruck,
    path: ROUTES.externalDispatch,
  },
  internalDispatch: {
    label: "Dispatch (From Warehouse)",
    icon: CiDeliveryTruck,
    path: ROUTES.internalDispatch,
  },
  transit: { label: "Transit", icon: CiDeliveryTruck, path: ROUTES.transit },
  receivedTrucks: {
    label: "Received Trucks",
    icon: CiDatabase,
    path: ROUTES.receivedVehicles,
  },
  dispatchedTrucks: {
    label: "Dispatched Trucks",
    icon: CiDeliveryTruck,
    path: ROUTES.dispatchedVehicles,
  },
  requests: {
    label: "Requests",
    icon: CiMedicalClipboard,
    path: ROUTES.requests,
  },
  productionRuns: {
    label: "Production Runs",
    icon: CiBoxList,
    path: ROUTES.productionRuns,
  },
  productSubmissions: {
    label: "Product Submissions",
    icon: CiBoxes,
    path: ROUTES.productSubmissions,
  },
  employees: {
    label: "Employees",
    icon: CiFaceSmile,
    path: ROUTES.employees,
  },
};

const {
  dashboard,
  warehouses,
  departments,
  positions,
  payrolls,
  userManagement,
  enrollment,
  stockRecords,
  externalStockRecords,
  inventoryItems,
  inventoryTransfers,
  purchases,
  sales,
  externalDispatch,
  internalDispatch,
  transit,
  receivedTrucks,
  dispatchedTrucks,
  requests,
  productionRuns,
  productSubmissions,
  employees,
  expenses,
} = menuItems;

export const superAdminMenuItems: SidebarMenuItem[] = [
  dashboard,
  warehouses,
  departments,
  positions,
  payrolls,
  userManagement,
  enrollment,
  stockRecords,
  externalStockRecords,
  inventoryItems,
  inventoryTransfers,
  purchases,
  sales,
  externalDispatch,
  internalDispatch,
  transit,
  receivedTrucks,
  dispatchedTrucks,
  requests,
  productionRuns,
  productSubmissions,
  employees,
];

export const adminMenuItems: SidebarMenuItem[] = [
  dashboard,
  warehouses,
  departments,
  positions,
  payrolls,
  userManagement,
  enrollment,
  stockRecords,
  externalStockRecords,
  inventoryItems,
  inventoryTransfers,
  purchases,
  sales,
  externalDispatch,
  internalDispatch,
  transit,
  receivedTrucks,
  dispatchedTrucks,
  productionRuns,
  employees,
];

export const productionMenuItems: SidebarMenuItem[] = [
  dashboard,
  stockRecords,
  requests,
  productionRuns,
  productSubmissions,
];
export const inventoryMenuItems: SidebarMenuItem[] = [
  dashboard,
  stockRecords,
  inventoryItems,
  internalDispatch,
  transit,
  receivedTrucks,
  dispatchedTrucks,
  requests,
  productSubmissions,
];
export const accountingMenuItems: SidebarMenuItem[] = [
  dashboard,
  payrolls,
  expenses,
  purchases,
  sales,
];
export const logisticsMenuItems: SidebarMenuItem[] = [
  dashboard,
  externalDispatch,
  transit,
  receivedTrucks,
];
export const managerMenuItems: SidebarMenuItem[] = [
  dashboard,
  departments,
  positions,
  payrolls,
  userManagement,
  enrollment,
  stockRecords,
  inventoryItems,
  sales,
  transit,
  receivedTrucks,
  dispatchedTrucks,
  requests,
  productionRuns,
  productSubmissions,
  employees,
  expenses,
];
export const defaultMenuItems: SidebarMenuItem[] = [menuItems.dashboard];
