const ROUTES = {
  home: "/",
  warehouses: "/warehouses",
  enrollment: "/enrollment",
  expenses: "/expenses",
  financialReports: "/financial-reports",
  departments: "/departments",
  positions: "/positions",
  payroll: "/payroll",
  inventoryItems: "/inventory-items",
  purchases: "/purchases",
  sales: "/sales",
  stockRecords: "/stock-records",
  externalStockRecords: "/external-stock-records",
  externalDispatch: "/external-dispatch",
  internalDispatch: "/internal-dispatch",
  transit: "/transit",
  scanWaybill: "/scan-waybill",
  dispatchedVehicles: "/dispatched-vehicles",
  receivedVehicles: "/received-vehicles",
  requests: "/requests",
  productionRuns: "/production-runs",
  productSubmissions: "/product-submissions",
  inventoryTransfers: "/inventory-transfers",
  employees: "/employees",
  transportFees: "/transportFees",
  userManagement: "/user-management",
  damages: "/damages",
  vehicleExpenses: "/vehicle-expenses",
};

export default ROUTES;
